# Generated by Django 4.2.1 on 2023-05-27 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 27, 21, 2, 28, 937750), verbose_name='To publish'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 27, 21, 2, 28, 938750), verbose_name='Date of the comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The author of the comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog', verbose_name='Comment Article')),
            ],
            options={
                'verbose_name': 'Comments on the blog article',
                'verbose_name_plural': 'Comments on blog articles',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
